#:==================================
#  List Behavior Config
#:==================================

# Model List Column configuration
list: ~/plugins/bm/field/models/category/columns.yaml

# Model Class name
modelClass: Bm\Field\Models\Category

# List Title
title: bm.field::lang.categories.list_title

# Link URL for each record
recordUrl: bm/field/categories/update/:id

# Message to display if the list is empty
noRecordsMessage: backend::lang.list.no_records

# Records to display per page
recordsPerPage: 0
showPagination: false
showTree: true
treeExpanded: true

# Display checkboxes next to each record
showCheckboxes: true

# Toolbar widget configuration
toolbar:
    # Partial for toolbar buttons
    buttons: list_toolbar

    # Search widget configuration
    search:
        prompt: backend::lang.list.search_prompt